name: CI

# Trigger this workflow on push or pull request
on: [push, pull_request]

jobs:
  build-win:
    name: Build (windows-latest)

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v1
      with:
        submodules: 'recursive'
    - name: CMake configure (default version)
      run: |
        ./initialize.bat
    - name: Build (default version)
      run: |
        cd build
        cmake --build . --config Release
    - name: Create Artifact Folder
      run: |
        mkdir artifact
        xcopy build/out_Release artifact /E /I /Q /Y
    - name: Create Build Artifact
      uses: actions/upload-artifact@v3
      with:
        name: APSudoku-win
        path: |
          artifact/*
  build-linux:
    name: Build (linux)

    runs-on: ubuntu-22.04

    steps:
    - uses: actions/checkout@v1
      with:
        submodules: 'recursive'
    - name: CMake configure (default version)
      run: |
        ./initialize.sh
    - name: Build (default version)
      run: |
        cd build
        cmake --build . --config Release
    - name: Create Artifact Folder
      run: |
        cp -r build/out_Release artifact
    - name: Create Build Artifact
      uses: actions/upload-artifact@v3
      with:
        name: APSudoku-win
        path: |
          artifact/*
