name: Release

on:
    workflow_dispatch:
        inputs:
            release-name:
                type: string
                description: English Name of the release
            release-tag:
                type: string
                description: Tag name of the release (ex 'v1.0.0')
            prerelease:
                type: boolean

jobs:
    build-win:
        name: Build (windows-latest)

        runs-on: windows-latest

        steps:
            - uses: actions/checkout@v1
              with:
                submodules: 'recursive'
            - name: CMake configure
              run: |
                    ./initialize.bat
            - name: Build
              run: |
                    cd build
                    cmake --build . --config Release
            - name: Package
              shell: python
              run: |
                    import shutil
                    from pathlib import Path
                    
                    path: Path = Path.cwd() / 'build/out_Release'
                    dest: Path = Path.cwd() / 'artifacts/APSudoku_Win_x64'
                    
                    shutil.make_archive(
                        base_name = dest,
                        format = 'zip',
                        root_dir = path
                        )
            - uses: actions/upload-artifact@v4
              name: win_x64_output
              with:
                path: 'artifacts/*'
    build-linux:
        name: Build (linux)

        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v1
              with:
                submodules: 'recursive'
            - name: CMake configure
              run: |
                    bash ./initialize.sh
            - name: Build
              run: |
                    cd build
                    cmake --build . --config Release
            - name: Package
              shell: python
              run: |
                    import shutil
                    from pathlib import Path
                    
                    path: Path = Path.cwd() / 'build/out_Release'
                    dest: Path = Path.cwd() / 'artifacts/APSudoku_Linux_x64'
                    
                    shutil.make_archive(
                        base_name = dest,
                        format = 'gztar',
                        root_dir = path
                        )
            - uses: actions/upload-artifact@v4
              name: linux_x64_output
              with:
                path: 'artifacts/*'
    publish:
        needs: ["build-linux","build-win"]
        runs-on: windows-latest
        steps:
            - uses: actions/download-artifact@v4
              with:
                path: packages
            - name: Release
              uses: softprops/action-gh-release@v1
              name: ${{ github.event.inputs.release-name }}
              tag_name: ${{ github.event.inputs.release-tag }}
              target_commitish: ${{ github.sha }}
              files: packages/*
              prerelease: ${{ github.event.inputs.prerelease }}
              fail_on_unmatched_files: true
              generate_release_notes: true